# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-14 21:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tags_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
    ]
