# Generated by Django 2.2 on 2019-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0003_auto_20190417_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract_type',
            field=models.IntegerField(blank=True, choices=[('', 'Any'), (0, 'Physical Good'), (1, 'Digital Good'), (2, 'Service')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='listingimage',
            unique_together={('listing', 'index', 'filename', 'original', 'large', 'medium', 'small', 'tiny')},
        ),
    ]
