# Generated by Django 2.2 on 2019-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0004_auto_20190425_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingoptions',
            unique_together={('listing', 'name')},
        ),
    ]
