# Generated by Django 2.2 on 2019-05-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0005_auto_20190425_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dog_follows',
        ),
    ]
